import { Combine, Scissors, FileImage, Images, Image as ImageIcon, Palette, FileText, FileType, FileSpreadsheet, Presentation, ScanLine, Archive, ShieldCheck, PenTool, CreditCard as Edit3, Sparkles, Wrench, FolderArchive, Briefcase, Code as Code2, Database, RotateCw, Gauge, Type, Lock, Clock as Unlock } from 'lucide-react';
import type { ToolDefinition } from './registry.types';
import { TOOL_SEO_CONTENT } from '../constants/toolSeoContent';

const lazy = (fn: () => Promise<{ default: React.ComponentType }>) => fn;

export const TOOL_REGISTRY: ToolDefinition[] = [
  {
    id: 'img-to-pdf',
    slug: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert JPG, PNG and WebP images into a single high-quality PDF.',
    category: 'conversion',
    icon: FileImage,
    component: () => import('../components/tools/ImgToPdfTool'),
    searchTerms: ['jpg to pdf', 'png to pdf', 'photo to pdf', 'picture to pdf', 'webp to pdf'],
    isPopular: true,
    processingMode: 'local',
    supportsBatch: true,
    maxFiles: 50,
    acceptedFormats: ['jpg', 'jpeg', 'png', 'webp'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Image to PDF Converter Online Free',
      description: 'Convert up to 50 images into a single PDF file online using DocBit. Fast document creation on mobile and desktop with no server uploads or account required.',
      keywords: ['image to pdf', 'jpg to pdf', 'png to pdf', 'photo to pdf', 'webp to pdf'],
      ogImage: 'https://res.cloudinary.com/dlesei0kn/image/upload/v1778171813/image-to-pdf_wxix5w.jpg',
    },
    faqs: [
      { q: 'Is DocBit Image to PDF converter free?', a: 'Yes, DocBit is 100% free with no hidden charges or premium subscriptions.' },
      { q: 'Are my images uploaded to any server?', a: 'No. DocBit uses on-device processing. Your images are converted to PDF directly in your browser and never touch our servers.' },
      { q: 'Can I use this tool on my mobile phone?', a: 'Absolutely! DocBit is fully optimized for mobile browsers, making it easy to create PDFs from your phone gallery.' },
    ],
    steps: [
      { name: 'Upload Images', text: 'Select or drag and drop JPG, PNG, or WebP image files.' },
      { name: 'Arrange Files', text: 'Reorder your images if needed by dragging them.' },
      { name: 'Configure Layout', text: 'Choose page size, orientation, margins and background color.' },
      { name: 'Convert and Download', text: 'Click "Export to PDF" and download your finished document.' },
    ],
    longContent: TOOL_SEO_CONTENT.imgToPdf,
  },
  {
    id: 'pdf-to-img',
    slug: 'pdf-to-images',
    name: 'PDF to Image',
    description: 'Convert PDF pages into high-quality JPG or PNG images.',
    category: 'conversion',
    icon: Images,
    component: () => import('../components/tools/PdfToImgTool'),
    searchTerms: ['pdf to jpg', 'pdf to png', 'pdf to image', 'extract images from pdf', 'pdf pages to images'],
    isPopular: true,
    processingMode: 'local',
    supportsBatch: true,
    maxFiles: 1,
    acceptedFormats: ['pdf'],
    outputFormats: ['jpg', 'png'],
    seo: {
      title: 'Convert PDF to JPG or PNG Online Free',
      description: 'Free PDF to image converter online. Convert PDF to JPG or PNG instantly. Extract PDF pages as high-quality images with fast, private processing on your device.',
      keywords: ['pdf to jpg', 'pdf to png', 'pdf to image', 'extract images from pdf'],
      ogImage: 'https://res.cloudinary.com/dlesei0kn/image/upload/v1778171813/pdf-to-images_kjjor5.jpg',
    },
    faqs: [
      { q: 'Can I convert multiple PDF pages to images at once?', a: 'Yes, DocBit extracts every page from your PDF and allows you to download them all as high-quality images.' },
      { q: 'Is there a limit on file size?', a: "Since processing is local, the only limit is your device's memory. We recommend files under 50MB for the best experience." },
      { q: 'Do I need to sign up to use DocBit?', a: 'No signup or account is required. You can start converting PDFs to images immediately.' },
    ],
    steps: [
      { name: 'Upload PDF', text: 'Select the PDF file you want to convert into images.' },
      { name: 'Choose Pages', text: 'Export all pages, a custom range, or select specific pages.' },
      { name: 'Select Format', text: 'Choose between PNG or JPG output format and quality.' },
      { name: 'Download Images', text: 'Download all images as a zip file.' },
    ],
    longContent: TOOL_SEO_CONTENT.pdfToImg,
  },
  {
    id: 'merge',
    slug: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into a single, organized document.',
    category: 'pdf',
    icon: Combine,
    component: () => import('../components/tools/MergeTool'),
    searchTerms: ['combine pdf', 'join pdf', 'merge pdf files', 'pdf merger', 'concatenate pdf'],
    isPopular: true,
    processingMode: 'local',
    supportsBatch: true,
    maxFiles: 10,
    acceptedFormats: ['pdf'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Merge PDF Files Online Free (Fast & Private)',
      description: 'Merge PDF files online free. Combine multiple PDFs into one document instantly with no upload. Fast, secure, and processed locally on your device.',
      keywords: ['merge pdf', 'combine pdf', 'join pdf', 'pdf merger'],
      ogImage: 'https://res.cloudinary.com/dlesei0kn/image/upload/v1778171812/merge-pdf_o8l7wm.jpg',
    },
    faqs: [
      { q: 'How many PDF files can I merge at once?', a: 'You can merge up to 10 PDF files at once. DocBit handles multiple files efficiently right in your browser.' },
      { q: 'Is merging PDFs on DocBit secure?', a: 'Extremely secure. Since your files are never uploaded to a server, your sensitive data stays on your machine.' },
      { q: 'Can I reorder files before merging?', a: 'Yes, you can easily move files up and down to change their sequence before clicking merge.' },
    ],
    steps: [
      { name: 'Upload PDF Files', text: 'Select multiple PDF documents you wish to combine.' },
      { name: 'Arrange Order', text: 'Move files up or down to set the preferred order.' },
      { name: 'Merge', text: 'Click the "Merge PDFs" button to combine them.' },
      { name: 'Download', text: 'Save the new single PDF file to your device.' },
    ],
    longContent: TOOL_SEO_CONTENT.merge,
  },
  {
    id: 'split',
    slug: 'split-pdf',
    name: 'Split PDF',
    description: 'Split a PDF into individual pages or extract only what you need.',
    category: 'pdf',
    icon: Scissors,
    component: () => import('../components/tools/SplitTool'),
    searchTerms: ['extract pdf pages', 'pdf splitter', 'separate pdf pages', 'divide pdf', 'pdf extractor'],
    isPopular: true,
    processingMode: 'local',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pdf'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Split PDF Online Free (Extract Pages Instantly)',
      description: 'Split PDF online free. Extract pages or separate PDF files instantly with no upload. Fast, secure, and processed entirely on your device.',
      keywords: ['split pdf', 'extract pdf pages', 'pdf splitter', 'separate pdf pages'],
      ogImage: 'https://res.cloudinary.com/dlesei0kn/image/upload/v1778171812/split-pdf_nmlgsz.jpg',
    },
    faqs: [
      { q: 'How do I extract a specific page range from a PDF?', a: 'Select the "Custom Range" mode, enter the page numbers you want, and DocBit will generate a new PDF with just those pages.' },
      { q: 'Does splitting a PDF reduce its quality?', a: 'No, DocBit preserves the original quality of your pages during the splitting process.' },
      { q: 'Is it safe to split sensitive documents here?', a: 'Yes. Because all splitting happens locally in your browser, your document contents are never transmitted over the internet.' },
    ],
    steps: [
      { name: 'Upload PDF', text: 'Select the PDF file you want to split.' },
      { name: 'Choose Strategy', text: 'Split into files, use a custom range, or extract selected pages.' },
      { name: 'Split', text: 'Click "Generate PDF" to process the file.' },
      { name: 'Download', text: 'Download your split PDF instantly.' },
    ],
    longContent: TOOL_SEO_CONTENT.split,
  },
  {
    id: 'grayscale-pdf',
    slug: 'grayscale-pdf',
    name: 'Grayscale PDF',
    description: 'Convert color PDFs to grayscale or black and white for efficient printing.',
    category: 'optimization',
    icon: Palette,
    component: () => import('../components/tools/GrayscaleTool'),
    searchTerms: ['black and white pdf', 'bw pdf', 'monochrome pdf', 'pdf to grayscale', 'desaturate pdf'],
    processingMode: 'local',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pdf'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Grayscale PDF Online Free (Black & White)',
      description: 'Convert color PDFs to grayscale or pure black and white online with DocBit. Fast, private, and secure browser-based document optimization.',
      keywords: ['grayscale pdf', 'black and white pdf', 'bw pdf', 'monochrome pdf'],
      ogImage: 'https://res.cloudinary.com/dlesei0kn/image/upload/v1778697040/Grayscale_pdf_uwrthg.jpg',
    },
    faqs: [
      { q: 'What is the difference between grayscale and black & white?', a: 'Grayscale uses different shades of gray to represent colors, while Black & White uses only black and white pixels, best for high-contrast documents like text scans.' },
      { q: 'Does grayscale conversion reduce file size?', a: 'Often yes! Removing color data can significantly reduce the file size, especially for documents with many color images.' },
      { q: 'Is the conversion high quality?', a: 'Yes, DocBit preserves text and image sharpness while converting colors to their equivalent luminance values.' },
    ],
    steps: [
      { name: 'Upload PDF', text: 'Select the color PDF you want to convert.' },
      { name: 'Choose Mode', text: 'Select "Grayscale" for shades of gray or "Pure B&W" for high contrast.' },
      { name: 'Select Pages', text: 'Convert all pages or only selected pages.' },
      { name: 'Download', text: 'Download your converted grayscale PDF instantly.' },
    ],
    longContent: TOOL_SEO_CONTENT.grayscalePdf,
  },

  // ---- Future tool placeholders (demonstrate 100+ scale architecture) ----
  // Each is marked comingSoon so it renders a teaser card but no route/page is built.
  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size while keeping quality.',
    category: 'compression',
    icon: Archive,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['reduce pdf size', 'pdf optimizer', 'shrink pdf', 'pdf compressor'],
    comingSoon: true,
    processingMode: 'local',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pdf'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Compress PDF Online Free',
      description: 'Reduce PDF file size while keeping quality. Coming soon to DocBit.',
      keywords: ['compress pdf', 'reduce pdf size', 'pdf optimizer'],
    },
  },
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF documents into editable Word files.',
    category: 'conversion',
    icon: FileType,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['pdf to docx', 'pdf to doc', 'pdf to word converter'],
    comingSoon: true,
    processingMode: 'cloud',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pdf'],
    outputFormats: ['docx'],
    seo: {
      title: 'PDF to Word Converter Online Free',
      description: 'Convert PDF documents into editable Word files. Coming soon to DocBit.',
      keywords: ['pdf to word', 'pdf to docx', 'pdf to doc'],
    },
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents into PDF format.',
    category: 'conversion',
    icon: FileText,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['docx to pdf', 'doc to pdf', 'word to pdf converter'],
    comingSoon: true,
    processingMode: 'cloud',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['docx', 'doc'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Word to PDF Converter Online Free',
      description: 'Convert Word documents into PDF format. Coming soon to DocBit.',
      keywords: ['word to pdf', 'docx to pdf', 'doc to pdf'],
    },
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets into PDF format.',
    category: 'conversion',
    icon: FileSpreadsheet,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['xlsx to pdf', 'xls to pdf', 'csv to pdf', 'spreadsheet to pdf'],
    comingSoon: true,
    processingMode: 'cloud',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['xlsx', 'xls', 'csv'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Excel to PDF Converter Online Free',
      description: 'Convert Excel spreadsheets into PDF format. Coming soon to DocBit.',
      keywords: ['excel to pdf', 'xlsx to pdf', 'csv to pdf'],
    },
  },
  {
    id: 'pdf-to-excel',
    slug: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract tables from PDF into editable Excel files.',
    category: 'conversion',
    icon: FileSpreadsheet,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['pdf to xlsx', 'pdf to csv', 'extract table from pdf'],
    comingSoon: true,
    processingMode: 'cloud',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pdf'],
    outputFormats: ['xlsx', 'csv'],
    seo: {
      title: 'PDF to Excel Converter Online Free',
      description: 'Extract tables from PDF into editable Excel files. Coming soon to DocBit.',
      keywords: ['pdf to excel', 'pdf to xlsx', 'pdf to csv'],
    },
  },
  {
    id: 'ppt-to-pdf',
    slug: 'ppt-to-pdf',
    name: 'PPT to PDF',
    description: 'Convert PowerPoint presentations into PDF.',
    category: 'conversion',
    icon: Presentation,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['pptx to pdf', 'ppt to pdf', 'powerpoint to pdf'],
    comingSoon: true,
    processingMode: 'cloud',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pptx', 'ppt'],
    outputFormats: ['pdf'],
    seo: {
      title: 'PPT to PDF Converter Online Free',
      description: 'Convert PowerPoint presentations into PDF. Coming soon to DocBit.',
      keywords: ['ppt to pdf', 'pptx to pdf', 'powerpoint to pdf'],
    },
  },
  {
    id: 'pdf-to-ppt',
    slug: 'pdf-to-ppt',
    name: 'PDF to PPT',
    description: 'Convert PDF pages into editable PowerPoint slides.',
    category: 'conversion',
    icon: Presentation,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['pdf to pptx', 'pdf to ppt', 'pdf to powerpoint'],
    comingSoon: true,
    processingMode: 'cloud',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pdf'],
    outputFormats: ['pptx'],
    seo: {
      title: 'PDF to PPT Converter Online Free',
      description: 'Convert PDF pages into editable PowerPoint slides. Coming soon to DocBit.',
      keywords: ['pdf to ppt', 'pdf to pptx', 'pdf to powerpoint'],
    },
  },
  {
    id: 'ocr',
    slug: 'ocr',
    name: 'OCR Text Extractor',
    description: 'Extract text from images and scanned documents.',
    category: 'ocr',
    icon: ScanLine,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['image to text', 'extract text from image', 'scan to text', 'ocr online'],
    comingSoon: true,
    processingMode: 'local',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['jpg', 'jpeg', 'png', 'webp'],
    outputFormats: ['txt'],
    seo: {
      title: 'OCR Text Extractor Online Free',
      description: 'Extract text from images and scanned documents. Coming soon to DocBit.',
      keywords: ['ocr', 'image to text', 'extract text from image'],
    },
  },
  {
    id: 'protect-pdf',
    slug: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add a password to your PDF documents.',
    category: 'security',
    icon: Lock,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['pdf password', 'encrypt pdf', 'secure pdf', 'lock pdf'],
    comingSoon: true,
    processingMode: 'local',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pdf'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Protect PDF with Password Online Free',
      description: 'Add a password to your PDF documents. Coming soon to DocBit.',
      keywords: ['protect pdf', 'pdf password', 'encrypt pdf', 'lock pdf'],
    },
  },
  {
    id: 'unlock-pdf',
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from PDF documents.',
    category: 'security',
    icon: Unlock,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['remove pdf password', 'decrypt pdf', 'unlock pdf'],
    comingSoon: true,
    processingMode: 'local',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pdf'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Unlock PDF Online Free',
      description: 'Remove password protection from PDF documents. Coming soon to DocBit.',
      keywords: ['unlock pdf', 'remove pdf password', 'decrypt pdf'],
    },
  },
  {
    id: 'sign-pdf',
    slug: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Add your signature to PDF documents.',
    category: 'signing',
    icon: PenTool,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['esign', 'e-signature', 'sign document', 'pdf signature'],
    comingSoon: true,
    processingMode: 'local',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pdf'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Sign PDF Online Free',
      description: 'Add your signature to PDF documents. Coming soon to DocBit.',
      keywords: ['sign pdf', 'esign', 'e-signature', 'pdf signature'],
    },
  },
  {
    id: 'rotate-pdf',
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate pages in a PDF document by 90, 180, or 270 degrees.',
    category: 'editing',
    icon: RotateCw,
    component: () => import('../components/tools/RotateTool'),
    searchTerms: ['rotate pdf pages', 'turn pdf', 'change pdf orientation', 'pdf rotator', 'flip pdf'],
    isPopular: true,
    isNew: true,
    processingMode: 'local',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pdf'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Rotate PDF Online Free (Rotate Pages Instantly)',
      description: 'Rotate PDF pages by 90, 180, or 270 degrees online free with DocBit. Fast, private, and secure browser-based rotation — no uploads required.',
      keywords: ['rotate pdf', 'rotate pdf pages', 'change pdf orientation', 'flip pdf', 'pdf rotator'],
      ogImage: 'https://res.cloudinary.com/dlesei0kn/image/upload/v1778171812/rotate-pdf.jpg',
    },
    faqs: [
      { q: 'Can I rotate only specific pages in my PDF?', a: 'Yes. Select the "Selected Pages" mode and pick individual pages to rotate, leaving the rest untouched.' },
      { q: 'Does rotating a PDF reduce its quality?', a: 'No. DocBit rotates pages by modifying page metadata, so text and images remain perfectly intact.' },
      { q: 'Is rotating PDFs on DocBit secure?', a: 'Absolutely. All rotation happens locally in your browser — your document never leaves your device.' },
    ],
    steps: [
      { name: 'Upload PDF', text: 'Select the PDF file you want to rotate.' },
      { name: 'Choose Angle', text: 'Pick 90, 180, or 270 degrees and select all or specific pages.' },
      { name: 'Rotate', text: 'Click "Rotate PDF" to apply the rotation.' },
      { name: 'Download', text: 'Download your rotated PDF instantly.' },
    ],
    longContent: TOOL_SEO_CONTENT.rotatePdf,
  },
  {
    id: 'compress-image',
    slug: 'compress-image',
    name: 'Compress Image',
    description: 'Reduce image file size without losing quality — batch compress up to 20 images.',
    category: 'compression',
    icon: Gauge,
    component: () => import('../components/tools/CompressImageTool'),
    searchTerms: ['image compressor', 'reduce image size', 'optimize image', 'compress jpg', 'compress png', 'compress webp'],
    isPopular: true,
    isNew: true,
    processingMode: 'local',
    supportsBatch: true,
    maxFiles: 20,
    acceptedFormats: ['jpg', 'jpeg', 'png', 'webp'],
    outputFormats: ['jpg', 'png', 'webp'],
    seo: {
      title: 'Compress Image Online Free (JPG, PNG, WebP)',
      description: 'Compress JPG, PNG, and WebP images online free with DocBit. Batch compress up to 20 images at once — fast, private, and processed entirely in your browser.',
      keywords: ['compress image', 'image compressor', 'reduce image size', 'compress jpg', 'compress png', 'optimize image'],
      ogImage: 'https://res.cloudinary.com/dlesei0kn/image/upload/v1778171812/compress-image.jpg',
    },
    faqs: [
      { q: 'How much can I reduce my image file size?', a: 'Depending on the quality level you choose, DocBit can reduce image size by 30% to 80% while keeping visual quality acceptable for most uses.' },
      { q: 'Can I compress multiple images at once?', a: 'Yes. DocBit supports batch compression of up to 20 images in a single session, all processed locally.' },
      { q: 'What image formats are supported?', a: 'DocBit supports JPG, PNG, and WebP formats for both input and output, with options to convert between them during compression.' },
    ],
    steps: [
      { name: 'Upload Images', text: 'Select or drag and drop JPG, PNG, or WebP image files.' },
      { name: 'Choose Quality', text: 'Pick a quality level from Low to Best and optionally set a max width or output format.' },
      { name: 'Compress', text: 'Click "Compress" to process your images locally.' },
      { name: 'Download', text: 'Download your compressed images individually or all at once.' },
    ],
    longContent: TOOL_SEO_CONTENT.compressImage,
  },
  {
    id: 'image-converter',
    slug: 'image-converter',
    name: 'Image Converter',
    description: 'Convert images between JPG, PNG, WebP, BMP, and GIF formats.',
    category: 'images',
    icon: ImageIcon,
    component: () => import('../components/tools/ImageConverterTool'),
    searchTerms: ['convert image', 'jpg to png', 'png to jpg', 'webp converter', 'bmp to png', 'gif to png'],
    isPopular: true,
    isNew: true,
    processingMode: 'local',
    supportsBatch: true,
    maxFiles: 20,
    acceptedFormats: ['jpg', 'jpeg', 'png', 'webp', 'bmp', 'gif'],
    outputFormats: ['jpg', 'png', 'webp'],
    seo: {
      title: 'Image Converter Online Free (JPG, PNG, WebP, BMP, GIF)',
      description: 'Convert images between JPG, PNG, WebP, BMP, and GIF formats online free with DocBit. Batch convert up to 20 images — fast, private, browser-only processing.',
      keywords: ['image converter', 'jpg to png', 'png to jpg', 'webp converter', 'bmp to png', 'gif to png', 'convert image format'],
      ogImage: 'https://res.cloudinary.com/dlesei0kn/image/upload/v1778171812/image-converter.jpg',
    },
    faqs: [
      { q: 'Which image formats can I convert between?', a: 'DocBit supports converting between JPG, PNG, and WebP as output formats, with BMP and GIF accepted as input formats.' },
      { q: 'Is there any quality loss when converting images?', a: 'Converting to PNG is lossless. Converting to JPG or WebP uses adjustable quality settings so you control the balance between size and fidelity.' },
      { q: 'Can I convert multiple images at once?', a: 'Yes. You can batch convert up to 20 images in a single session, all processed locally in your browser.' },
    ],
    steps: [
      { name: 'Upload Images', text: 'Select or drag and drop the images you want to convert.' },
      { name: 'Choose Format', text: 'Pick the target format (JPG, PNG, or WebP) and adjust quality if applicable.' },
      { name: 'Convert', text: 'Click "Convert" to process your images locally.' },
      { name: 'Download', text: 'Download your converted images individually or all at once.' },
    ],
    longContent: TOOL_SEO_CONTENT.imageConverter,
  },
  {
    id: 'text-to-pdf',
    slug: 'text-to-pdf',
    name: 'Text to PDF',
    description: 'Convert plain text or Markdown files into formatted PDF documents.',
    category: 'text',
    icon: Type,
    component: () => import('../components/tools/TextToPdfTool'),
    searchTerms: ['txt to pdf', 'text file to pdf', 'notepad to pdf', 'markdown to pdf', 'md to pdf'],
    isNew: true,
    processingMode: 'local',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['txt', 'md'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Text to PDF Converter Online Free (TXT & Markdown)',
      description: 'Convert plain text and Markdown files into formatted PDF documents online free with DocBit. Choose fonts, alignment, page size, and spacing — all processed locally.',
      keywords: ['text to pdf', 'txt to pdf', 'text file to pdf', 'markdown to pdf', 'md to pdf', 'notepad to pdf'],
      ogImage: 'https://res.cloudinary.com/dlesei0kn/image/upload/v1778171812/text-to-pdf.jpg',
    },
    faqs: [
      { q: 'Can I customize the formatting of my PDF?', a: 'Yes. DocBit lets you choose font family (Helvetica, Times, Courier), font size, text alignment, page size, line height, and paragraph spacing.' },
      { q: 'Does DocBit support Markdown files?', a: 'Yes. You can upload .md files and DocBit will render the text content into a formatted PDF. Note that Markdown syntax is treated as plain text.' },
      { q: 'Is there a file size limit?', a: 'Text files up to 10MB are supported, which is more than enough for even the longest documents.' },
    ],
    steps: [
      { name: 'Upload Text File', text: 'Select a .txt or .md file to convert.' },
      { name: 'Configure Formatting', text: 'Choose font, size, alignment, page size, and spacing.' },
      { name: 'Convert', text: 'Click "Export PDF" to generate your document.' },
      { name: 'Download', text: 'Download your formatted PDF instantly.' },
    ],
    longContent: TOOL_SEO_CONTENT.textToPdf,
  },
  {
    id: 'zip-extractor',
    slug: 'zip-extractor',
    name: 'Unzip / Extract',
    description: 'Extract files from ZIP archives entirely in your browser.',
    category: 'archives',
    icon: FolderArchive,
    component: () => import('../components/tools/UnzipTool'),
    searchTerms: ['unzip', 'extract zip', 'zip extractor', 'decompress', 'unzip online', 'zip file opener'],
    isPopular: true,
    isNew: true,
    processingMode: 'local',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['zip'],
    outputFormats: [],
    seo: {
      title: 'Unzip Files Online Free (Extract ZIP in Browser)',
      description: 'Extract files from ZIP archives online free with DocBit. No uploads, no software install — unzip up to 500MB archives entirely in your browser with total privacy.',
      keywords: ['unzip', 'extract zip', 'zip extractor', 'decompress', 'unzip online', 'zip file opener'],
      ogImage: 'https://res.cloudinary.com/dlesei0kn/image/upload/v1778171812/unzip-extractor.jpg',
    },
    faqs: [
      { q: 'How large a ZIP file can I extract?', a: 'DocBit supports ZIP archives up to 500MB. Since processing is local, the only real limit is your device\'s available memory.' },
      { q: 'Can I download individual files from the archive?', a: 'Yes. After extraction, you can download files individually or re-package them into a new ZIP.' },
      { q: 'Is it safe to extract sensitive archives here?', a: 'Absolutely. All extraction happens in your browser — your files are never uploaded to any server.' },
    ],
    steps: [
      { name: 'Upload ZIP', text: 'Select the ZIP archive you want to extract.' },
      { name: 'Choose Output', text: 'Pick individual file downloads or re-package into a new ZIP.' },
      { name: 'Extract', text: 'Click "Extract" to process the archive locally.' },
      { name: 'Download', text: 'Download your files individually or as a new ZIP.' },
    ],
    longContent: TOOL_SEO_CONTENT.zipExtractor,
  },
  {
    id: 'ai-summarize',
    slug: 'ai-summarize',
    name: 'AI Summarize',
    description: 'Summarize long documents with AI.',
    category: 'ai',
    icon: Sparkles,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['summarize pdf', 'ai summary', 'document summary'],
    comingSoon: true,
    processingMode: 'cloud',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pdf', 'txt'],
    outputFormats: ['txt'],
    seo: {
      title: 'AI Document Summarizer Online Free',
      description: 'Summarize long documents with AI. Coming soon to DocBit.',
      keywords: ['ai summarize', 'summarize pdf', 'document summary'],
    },
  },
  {
    id: 'edit-pdf',
    slug: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, shapes and annotations to PDF documents.',
    category: 'editing',
    icon: Edit3,
    component: () => import('../components/tools/ComingSoonTool'),
    searchTerms: ['edit pdf', 'annotate pdf', 'pdf editor', 'add text to pdf'],
    comingSoon: true,
    processingMode: 'local',
    supportsBatch: false,
    maxFiles: 1,
    acceptedFormats: ['pdf'],
    outputFormats: ['pdf'],
    seo: {
      title: 'Edit PDF Online Free',
      description: 'Add text, shapes and annotations to PDF documents. Coming soon to DocBit.',
      keywords: ['edit pdf', 'annotate pdf', 'pdf editor'],
    },
  },
];

export const TOOL_MAP: Record<string, ToolDefinition> = Object.fromEntries(
  TOOL_REGISTRY.map((t) => [t.slug, t])
);

export const getToolBySlug = (slug: string): ToolDefinition | undefined => TOOL_MAP[slug];

export const getActiveTools = (): ToolDefinition[] => TOOL_REGISTRY.filter((t) => !t.comingSoon);

export const getComingSoonTools = (): ToolDefinition[] => TOOL_REGISTRY.filter((t) => t.comingSoon);

export const getPopularTools = (): ToolDefinition[] => TOOL_REGISTRY.filter((t) => t.isPopular && !t.comingSoon);

export const getNewTools = (): ToolDefinition[] => TOOL_REGISTRY.filter((t) => t.isNew && !t.comingSoon);

export const getToolsByCategory = (category: string): ToolDefinition[] =>
  TOOL_REGISTRY.filter((t) => t.category === category && !t.comingSoon);

export const searchTools = (query: string): ToolDefinition[] => {
  const q = query.toLowerCase().trim();
  if (!q) return getActiveTools();
  return TOOL_REGISTRY.filter((t) => {
    if (t.comingSoon) return false;
    const haystack = [t.name, t.description, t.category, ...(t.searchTerms || []), ...t.seo.keywords]
      .join(' ')
      .toLowerCase();
    return haystack.includes(q);
  });
};
